# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.10
  - 3.9
  - 3.8
  - 3.7


# Command to install dependencies
install: pip install -U tox-travis

# Command to run tests
script: tox


